services:
  dev:
    image: kkittur/drivebrain_cross_compile
    volumes:
      - conan-cache:/root/.conan2
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: sleep infinity
    restart: "no"

volumes:
  conan-cache:
